### ISSUE TITLE
Can't create PR.

### ISSUE THREAD

**Issue by thomasward1212** [asztal/react-intl-modules-loader#1]
![image](https://user-images.githubusercontent.com/16187432/46198740-189d1280-c305-11e8-9abc-d614a2cabdb4.png)

**Comment by asztal** [comment]
I've added you as a collaborator, this better not be a Fork-Delete-Pullrequest ;)

P.s. there may be much better and more maintained approaches to this problem since I made this. I think there's a Babel plugin which might work better

**Comment by tomtomdotcom** [comment]
👋 new tom is here

**Comment by asztal** [comment]
I'm closing this because I am archiving this repo

`F`
